"""
Django settings for devsync project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from collections import OrderedDict
from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'devsync-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [

    # overrides
    'admin.apps.DevSyncAdminConfig', #overrides 'django.contrib.admin'

    # native
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3ª party
    'rest_framework.apps.RestFrameworkConfig',

    # core
    'core.users.apps.UserConfig',

    # main
    'main.record.apps.RecordConfig',
]

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = '/devsync/login/'
LOGIN_REDIRECT_URL = '/devsync/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'core.identity.middleware.MsalMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(BASE_DIR / 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'devsync.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = BASE_DIR / 'var' / 'static_root'
STATIC_URL = '/devsync/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# MEDIA STORAGE
MEDIA_URL = '/documents/'
MEDIA_ROOT = BASE_DIR / 'documents'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging file
# https://docs.djangoproject.com/en/3.2/topics/logging/
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'log' / 'devsync.log'),
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'werkzeug': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Django Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
}

ADMIN_OVERRIDES = OrderedDict([
    # ('<admin section title>', [..., ('<app_label>', '<model_name>', '<admin model verbose name>')])
    ('Registro e Autorização', [
        ('users', 'User', 'Usuário', 'Usuários', True),
        ('auth', 'Group', 'Grupo', 'Grupos', True),
    ]),
    ('Documentos', [
        ('record', 'Document', 'Documento', 'Documentos', True)
    ]),
    ('DevSync', [
        ('record', 'CoachCoacheesRelation', 'Relação Mentor-Participantes', 'Relações Mentor-Participantes', True),
        ('record', 'Meeting', 'Reunião', 'Reuniões', True),
        ('record', 'Skill', 'Competência', 'Competências', True),
    ])
    # ('Advanced', [
    #     ('insight', 'InsightNotifier', 'Insight Rule', 'Insight Rules', True),
    #     ('dynamicattributes', 'DynamicAttributeDefinition', 'Field Attribute', 'Field Attributes', True),
    #     ('contenttypes', 'ContentType', 'Field Attribute Value', 'Field Attribute Values', True),
    # ]),
    # ('Hidden', [
    #     ('dynamicattributes', 'FieldAttributeValue', 'Field Attribute Value', 'Field Attribute Values', False),
    # ]),
])

# MSAL AUTHENTICATION
IDENTITY_CONFIG = {
    'id_web_configs': 'MS_ID_WEB_CONFIGS',
    'graph_url': 'https://graph.microsoft.com/v1.0',
    'client': {
        'client_id': os.environ.get('MS_CLIENT_ID', ''),
        'client_credential': os.environ.get('MS_CLIENT_SECRET', ''),
        'authority': 'https://login.microsoftonline.com/' + os.environ.get('MS_TENANT_ID', ''),
    },
    'auth_request': {
        'scopes': ['User.Read'],
        'response_type': 'code'
    },
}
IDENTITY_ENABLED = bool(os.environ.get('MS_CLIENT_ID'))
if IDENTITY_ENABLED:
    from core.identity import IdentityWebPython
    IDENTITY_IDENTITY_WEB = IdentityWebPython()
else:
    IDENTITY_IDENTITY_WEB = None
if not IDENTITY_ENABLED:
    MIDDLEWARE.remove('core.identity.middleware.MsalMiddleware')


if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
