# Generated by Django 3.2.4 on 2022-09-13 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.record.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCoacheesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachcoachees_coach', to=settings.AUTH_USER_MODEL, unique=True, validators=[main.record.models.coach_user_validator], verbose_name='Coach')),
            ],
            options={
                'verbose_name': 'Relação Coach-Coachees',
                'verbose_name_plural': 'Relações Coach-Coachees',
            },
        ),
        migrations.CreateModel(
            name='CoacheesCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_coachees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachcoachees', to='record.coachcoacheesrelation')),
                ('coachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachcoachees_coachee', to=settings.AUTH_USER_MODEL, unique=True, validators=[main.record.models.coachee_user_validator], verbose_name='Coachee')),
            ],
            options={
                'verbose_name': 'Coachee',
                'verbose_name_plural': 'Coachees',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
                ('file', models.FileField(upload_to='', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Comentário')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('coach_coachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='record.coacheescoach', verbose_name='Coach | Coachee')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-date_update', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('level', models.CharField(choices=[('L', 'liderança'), ('P', 'profissional')], max_length=2, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('N', 'em andamento'), ('P', 'em atraso'), ('C', 'concluído')], default='N', max_length=1, verbose_name='Status')),
                ('date_task_create', models.DateField(auto_now_add=True)),
                ('date_task_update', models.DateField(auto_now=True)),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('date_concluded', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('note', models.TextField(blank=True, verbose_name='Comentário')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='record.meeting', verbose_name='Reunião')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='record.skill', verbose_name='Competência')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-date_task_update', '-id'],
            },
        ),
        migrations.AddField(
            model_name='coachcoacheesrelation',
            name='coachees',
            field=models.ManyToManyField(through='record.CoacheesCoach', to=settings.AUTH_USER_MODEL),
        ),
    ]
