# Generated by Django 5.2.17 on 2026-10-07 12:42

import django.db.models.deletion
import main.record.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachcoacheesrelation',
            options={'verbose_name': 'Relação Mentor-Participantes', 'verbose_name_plural': 'Relações Mentor-Participantes'},
        ),
        migrations.AlterField(
            model_name='coachcoacheesrelation',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachcoachees_coach', to=settings.AUTH_USER_MODEL, unique=True, validators=[main.record.models.coach_user_validator], verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='coacheescoach',
            name='coachee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachcoachees_coachee', to=settings.AUTH_USER_MODEL, unique=True, validators=[main.record.models.coachee_user_validator], verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='coach_coachee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='record.coacheescoach', verbose_name='Mentor | Participante'),
        ),
    ]
