# Generated by Django 5.2.17 on 2026-10-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_coachcoacheesrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coacheescoach',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
