# Generated by Django 3.2.4 on 2022-09-13 14:18

import core.users.managers
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(editable=False, max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('DIR', 'Diretor'), ('GSN', 'Gerente senior'), ('GST', 'Gerente de tecnologia senior'), ('G5N', 'Gerente 5'), ('G5T', 'Gerente de tecnologia 5'), ('G4N', 'Gerente 4'), ('G4T', 'Gerente de tecnologia 4'), ('G3N', 'Gerente 3'), ('G3T', 'Gerente de tecnologia 3'), ('G2N', 'Gerente 2'), ('G2T', 'Gerente de tecnologia 2'), ('G1N', 'Gerente 1'), ('G1T', 'Gerente de tecnologia 1'), ('CS4', 'Consultor senior 4'), ('CT4', 'Consultor de tecnologia senior 4'), ('CS3', 'Consultor senior 3'), ('CT3', 'Consultor de tecnologia senior 3'), ('CS2', 'Consultor senior 2'), ('CT2', 'Consultor de tecnologia senior 2'), ('CS1', 'Consultor senior 1'), ('CT1', 'Consultor de tecnologia senior 1'), ('AN3', 'Analista de negocios 3'), ('AT3', 'Analista de tecnologia 3'), ('AN2', 'Analista de negocios 2'), ('AT2', 'Analista de tecnologia 2'), ('AN1', 'Analista de negocios 1'), ('AT1', 'Analista de tecnologia 1'), ('AST', 'Assistente tecnico')], max_length=3, verbose_name='Cargo')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='Área')),
                ('service', models.CharField(blank=True, max_length=50, verbose_name='Serviço')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.users.managers.CustomUserManager()),
            ],
        ),
    ]
