# Generated by Django 5.2.17 on 2026-10-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEV', 'Desenvolvedor'), ('TEC', 'Especialista técnico'), ('LID', 'Líder de equipe'), ('GES', 'Gestor'), ('OUT', 'Outro')], max_length=3, verbose_name='Cargo'),
        ),
    ]
